version: '2'

services:

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    env_file: .env
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    restart: always
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - app-network

  web:
    build: .
    command: bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn traffic_manager.wsgi:application --workers 4 --bind 0.0.0.0:8000"
    container_name: web
    volumes:
      - .:/code
      - static:/code/static
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - app-network

  qcluster:
    build: .
    command: bash -c "
      python manage.py migrate &&
      python manage.py qcluster"
    container_name: web
    volumes:
      - .:/code
      - static:/code/static
    depends_on:
      - db
      - web
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static:/code/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot:v0.36.0
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/certbot --email not_provided@gmail.com --agree-tos --no-eff-email --force-renewal -d client.news.te.ua -d www.client.news.te.ua

volumes:
  db:
  pgadmin:
  static:

networks:
  app-network:
    driver: bridge
