version: '3'

services:

  db_django_psql:
    image: postgres
    container_name: db_django_psql
    ports:
      - '5432:5432'
    env_file: .env
    restart: always
    volumes:
      - db_django_psql:/var/lib/postgresql/data/
    networks:
      - postgres


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    restart: always
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

volumes:
  db_django_psql:
  pgadmin:

networks:
  postgres:
    driver: bridge
