version: '2'

services:

  tm_db:
    image: postgres
    container_name: tm_db
    ports:
      - 5432:5432
    env_file: .env
    restart: always
    volumes:
      - tm_db:/var/lib/postgresql/data/
    networks:
      - app-network

  tm_pgadmin:
    container_name: tm_pgadmin
    image: dpage/pgadmin4
    env_file: .env
    restart: always
    volumes:
       - tm_pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - app-network

  tm_web:
    build: .
    command: gunicorn traffic_manager.wsgi:application --workers 2 --bind 0.0.0.0:8000
    container_name: tm_web
    volumes:
      - .:/code
      - ./static:/code/static
    expose:
      - 8000
    depends_on:
      - tm_db
    networks:
      - app-network

  tm_nginx:
    build: ./nginx
    container_name: tm_nginx
    volumes:
      - ./static:/code/static
    ports:
      - 8000:80
    depends_on:
      - tm_web
    networks:
      - app-network

volumes:
  tm_db:
  tm_pgadmin:

networks:
  app-network:
    driver: bridge
