# Generated by Django 3.1.4 on 2021-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictarget',
            name='traffic',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
