# Generated by Django 3.1.5 on 2021-01-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210111_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(help_text='Посилання на RSS стрічку', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
