# Generated by Django 3.1.4 on 2021-03-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_source_remaining_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictarget',
            name='limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
