# Generated by Django 3.1.5 on 2021-01-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_statictarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictarget',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
