# Generated by Django 3.1.4 on 2021-01-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210111_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='title',
            field=models.CharField(default='Немає', max_length=200),
        ),
    ]
