# Generated by Django 3.1.4 on 2021-03-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_statictarget_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statictarget',
            name='last_reset_at',
        ),
    ]
