# Generated by Django 3.1.4 on 2021-06-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_statictarget_last_reset_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='url',
            field=models.URLField(help_text='Посилання, яке поміщатиметься в iframe у віджеті', max_length=400),
        ),
    ]
